/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.lentrix.demos.ui;

import com.lentrix.demos.db.CarDAO;
import com.lentrix.demos.models.Car;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentrix
 */
public class CarsForm extends javax.swing.JDialog {
    private Car currentCar = null;
    private List<Car> carList = null;
    /**
     * Creates new form CustomersForm
     */
    public CarsForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            carList = CarDAO.getAll();
            tabulate();
        }catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),"Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void tabulate() throws Exception {
        String[] headers = {"Make", "Model", "Color", "Year", "Plate"};
        
        DefaultTableModel model = new DefaultTableModel(headers, 0);
        
        for(Car c: carList) {
            model.addRow(new Object[] {c.getMake(), c.getModel(), c.getYear(), c.getPlate()});
        }
        
        carsTable.setModel(model);
        carsTable.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        makeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        modelTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        colorTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        plateTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        yearTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        newBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        findBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        carsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customers Form");

        jPanel1.setLayout(new java.awt.GridLayout(10, 1, 5, 5));

        jLabel1.setText("Make");
        jPanel1.add(jLabel1);
        jPanel1.add(makeTxt);

        jLabel2.setText("Model");
        jPanel1.add(jLabel2);
        jPanel1.add(modelTxt);

        jLabel3.setText("Color");
        jPanel1.add(jLabel3);
        jPanel1.add(colorTxt);

        jLabel4.setText("Plate");
        jPanel1.add(jLabel4);
        jPanel1.add(plateTxt);

        jLabel5.setText("Year");
        jPanel1.add(jLabel5);
        jPanel1.add(yearTxt);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 8, 3));

        newBtn.setText("New");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });
        jPanel2.add(newBtn);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(saveBtn);

        findBtn.setText("Find");
        jPanel2.add(findBtn);

        deleteBtn.setText("Delete");
        jPanel2.add(deleteBtn);

        jPanel3.setLayout(new java.awt.BorderLayout());

        carsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(carsTable);

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Raleway Semi-Bold", 0, 36)); // NOI18N
        jLabel6.setText("Cars Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 939, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1307, 712));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed
        currentCar = null;
        clearFields();
    }//GEN-LAST:event_newBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        if(currentCar==null) {
                
            try {
                Car c = new Car(
                    -1, makeTxt.getText(), 
                    modelTxt.getText(), 
                    colorTxt.getText(), 
                    plateTxt.getText(), 
                    Integer.parseInt(yearTxt.getText())
                );
                
                StringBuffer errors = new StringBuffer();
                if(c.validate(errors)) {
                    CarDAO.add(c);
                    JOptionPane.showMessageDialog(this, "A new car has been added to the record.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                }else {
                    JOptionPane.showMessageDialog(this, errors.toString(), "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "You entered an invalid year.", "Error!", JOptionPane.ERROR_MESSAGE);
            }catch(Exception ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            }
        }else {
            try {
                
                currentCar.setMake(makeTxt.getText());
                currentCar.setModel(modelTxt.getText());
                currentCar.setColor(colorTxt.getText());
                currentCar.setPlate(plateTxt.getText());
                currentCar.setYear(Integer.parseInt(yearTxt.getText()));
                
                StringBuffer errors = new StringBuffer();
                
                if(currentCar.validate(errors)) {
                    
                    CarDAO.update(currentCar);
                    JOptionPane.showMessageDialog(this, "Car has been updated.", "Updated!", JOptionPane.INFORMATION_MESSAGE);                    
                    tabulate();
                    
                }else {
                    JOptionPane.showMessageDialog(this, errors.toString(), "Error!", JOptionPane.ERROR_MESSAGE);
                }
            }catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "The year is invalid", "Error!", JOptionPane.ERROR_MESSAGE);                                
            }catch(Exception ex) {
                JOptionPane.showMessageDialog(this,ex.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);                
            }
        }
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void carsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carsTableMouseClicked
        int index = carsTable.getSelectedRow();
        
        currentCar = carList.get(index);
        
        if(currentCar != null) {
            //populate data to form
            makeTxt.setText(currentCar.getMake());
            modelTxt.setText(currentCar.getModel());
            colorTxt.setText(currentCar.getColor());
            yearTxt.setText(String.valueOf(currentCar.getYear()));
            plateTxt.setText(currentCar.getPlate());
            
            makeTxt.grabFocus();
        }
    }//GEN-LAST:event_carsTableMouseClicked

    private void clearFields() {
        makeTxt.setText(null);
        modelTxt.setText(null);
        colorTxt.setText(null);
        plateTxt.setText(null);
        yearTxt.setText(null);
        makeTxt.grabFocus();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarsForm dialog = new CarsForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable carsTable;
    private javax.swing.JTextField colorTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton findBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField makeTxt;
    private javax.swing.JTextField modelTxt;
    private javax.swing.JButton newBtn;
    private javax.swing.JTextField plateTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField yearTxt;
    // End of variables declaration//GEN-END:variables
}
